### ISSUE TITLE
Can't execute benchmark with Dart 1.12.1

### ISSUE THREAD

**Issue by natorion** [dart-lang/ton80#36]
-I downloaded https://storage.googleapis.com/dart-archive/channels/stable/release/1.12.1/sdk/dartsdk-linux-x64-release.zip
-extracted it to '~/dart/dart-sdk/'.
-Downloaded ton80 and put it to '~/tmp/dartPerf/ton80'
-'cd ~/tmp/dartPerf/ton80'
-'~/dart/dart-sdk/bin/pub get' in the benchmarks' directory
-'~/dart/dart-sdk/bin/dart bin/ton80.dart'
-Result:

############
foo@bar:~/tmp/dartPerf/ton80$ ~/dart/dart-sdk/bin/dart bin/ton80.dart 
Running DeltaBlue...
  - Dart    :   899.50 runs/sec (893.26±0.3%)
Unhandled exception:
ProcessException: No such file or directory
  Command: d8 /...home.../tmp/dartPerf/ton80/bin/../lib/src/DeltaBlue/dart/DeltaBlue.dart.js
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:474)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:626)
#2      Process.runSync (dart:io-patch/process_patch.dart:64)
#3      Dart2JSRunner.run.<anonymous closure> (file:///...home.../tmp/dartPerf/ton80/bin/ton80.dart:108:49)
#4      extractScores (file:///...home.../tmp/dartPerf/ton80/bin/ton80.dart:203:40)
#5      Dart2JSRunner.run (file:///...home.../tmp/dartPerf/ton80/bin/ton80.dart:108:18)
#6      main (file:///...home.../tmp/dartPerf/ton80/bin/ton80.dart:86:16)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
############

**Comment by floitschG** [comment]
The ton80 benchmarks seem to require d8 to run the JS versions (output of dart2js and pure JS). You can use the --js/-j flag to tell ton80 where it can find the executable.

As a work-around, if you just want to run the Dart benchmarks without comparing them to JavaScript, you can delete lines 20 and 21 of `bin/ton80.dart`.

**Comment by natorion** [comment]
I created a pull request in the hope next person can solve the problem alone.
